import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const classPresets = [
  {
    id: "artificer",
    name: "Artificer",
    source: "EFA",
    description:
      "Inventor arcano que mezcla herramientas, magia e infusiones. Preset estructural sin texto de libro.",
    hitDie: 8,
    primaryAbilities: ["INT"],
    savingThrows: ["CON", "INT"],
    armorTraining: ["Light Armor", "Medium Armor", "Shields"],
    weaponTraining: ["Simple Weapons"],
    toolTraining: ["Thieves' Tools", "Tinker's Tools", "One artisan tool"],
    skillChoices: [
      "Arcana",
      "History",
      "Investigation",
      "Medicine",
      "Nature",
      "Perception",
      "Sleight of Hand",
    ],
    skillChoiceCount: 2,
    spellcastingType: "HALF_PREPARED_ROUNDED_UP",
    spellcastingAbility: "INT",
    isOfficial: true,
    isSrd: false,
    features: [
      { level: 1, name: "Magical Tinkering", summary: "Efectos mágicos menores aplicados a objetos." },
      { level: 1, name: "Spellcasting", summary: "Lanzamiento de conjuros basado en Inteligencia." },
      { level: 2, name: "Infuse Item", summary: "Convierte objetos comunes en objetos mágicos temporales." },
      { level: 3, name: "Artificer Specialist", summary: "Elección de especialización de artificiero." },
      { level: 3, name: "The Right Tool for the Job", summary: "Crea herramientas apropiadas usando herramientas de artesano." },
      { level: 4, name: "Ability Score Improvement", summary: "Mejora característica o elige dote si tu mesa lo permite." },
      { level: 5, name: "Specialist Feature", summary: "Rasgo entregado por la especialización." },
      { level: 6, name: "Tool Expertise", summary: "Mejora el uso de herramientas con competencia." },
      { level: 7, name: "Flash of Genius", summary: "Apoyo reactivo a pruebas o salvaciones cercanas." },
      { level: 10, name: "Magic Item Adept", summary: "Mejora interacción con objetos mágicos." },
      { level: 11, name: "Spell-Storing Item", summary: "Almacena un conjuro en un objeto para usos posteriores." },
      { level: 14, name: "Magic Item Savant", summary: "Mejora avanzada con objetos mágicos." },
      { level: 18, name: "Magic Item Master", summary: "Dominio superior de objetos mágicos." },
      { level: 20, name: "Soul of Artifice", summary: "Rasgo final defensivo ligado a objetos mágicos." },
    ],
  },
  {
    id: "barbarian",
    name: "Barbarian",
    source: "SRD 5.1",
    description:
      "Guerrero resistente de combate físico y furia primal.",
    hitDie: 12,
    primaryAbilities: ["STR"],
    savingThrows: ["STR", "CON"],
    armorTraining: ["Light Armor", "Medium Armor", "Shields"],
    weaponTraining: ["Simple Weapons", "Martial Weapons"],
    toolTraining: [],
    skillChoices: [
      "Animal Handling",
      "Athletics",
      "Intimidation",
      "Nature",
      "Perception",
      "Survival",
    ],
    skillChoiceCount: 2,
    spellcastingType: "NONE",
    spellcastingAbility: null,
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Rage", summary: "Estado de combate que aumenta daño físico y resistencia." },
      { level: 1, name: "Unarmored Defense", summary: "Defensa sin armadura usando Constitución." },
      { level: 2, name: "Reckless Attack", summary: "Ataque arriesgado con ventaja y desventaja defensiva." },
      { level: 2, name: "Danger Sense", summary: "Instinto para evitar ciertos peligros visibles." },
      { level: 3, name: "Primal Path", summary: "Elección de camino bárbaro." },
      { level: 5, name: "Extra Attack", summary: "Ataque adicional al tomar la acción de atacar." },
      { level: 5, name: "Fast Movement", summary: "Aumento de velocidad sin armadura pesada." },
    ],
  },
  {
    id: "bard",
    name: "Bard",
    source: "SRD 5.1",
    description:
      "Lanzador carismático versátil con apoyo, magia y habilidades.",
    hitDie: 8,
    primaryAbilities: ["CHA"],
    savingThrows: ["DEX", "CHA"],
    armorTraining: ["Light Armor"],
    weaponTraining: ["Simple Weapons", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    toolTraining: ["Three musical instruments"],
    skillChoices: [
      "Acrobatics",
      "Animal Handling",
      "Arcana",
      "Athletics",
      "Deception",
      "History",
      "Insight",
      "Intimidation",
      "Investigation",
      "Medicine",
      "Nature",
      "Perception",
      "Performance",
      "Persuasion",
      "Religion",
      "Sleight of Hand",
      "Stealth",
      "Survival",
    ],
    skillChoiceCount: 3,
    spellcastingType: "FULL_KNOWN",
    spellcastingAbility: "CHA",
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Spellcasting", summary: "Lanzamiento de conjuros basado en Carisma." },
      { level: 1, name: "Bardic Inspiration", summary: "Inspira a aliados para mejorar tiradas." },
      { level: 2, name: "Jack of All Trades", summary: "Bonificación parcial a pruebas sin competencia." },
      { level: 2, name: "Song of Rest", summary: "Mejora recuperación durante descansos cortos." },
      { level: 3, name: "Bard College", summary: "Elección de colegio de bardo." },
      { level: 3, name: "Expertise", summary: "Mejora competencias elegidas." },
      { level: 10, name: "Magical Secrets", summary: "Aprende conjuros fuera de la lista normal." },
    ],
  },
  {
    id: "cleric",
    name: "Cleric",
    source: "SRD 5.1",
    description:
      "Lanzador divino preparado, enfocado en Sabiduría, dominios y apoyo.",
    hitDie: 8,
    primaryAbilities: ["WIS"],
    savingThrows: ["WIS", "CHA"],
    armorTraining: ["Light Armor", "Medium Armor", "Shields"],
    weaponTraining: ["Simple Weapons"],
    toolTraining: [],
    skillChoices: ["History", "Insight", "Medicine", "Persuasion", "Religion"],
    skillChoiceCount: 2,
    spellcastingType: "FULL_PREPARED",
    spellcastingAbility: "WIS",
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Spellcasting", summary: "Lanzamiento de conjuros preparado basado en Sabiduría." },
      { level: 1, name: "Divine Domain", summary: "Elección de dominio clerical." },
      { level: 2, name: "Channel Divinity", summary: "Uso de poder divino especial." },
      { level: 5, name: "Destroy Undead", summary: "Mejora contra muertos vivientes." },
      { level: 10, name: "Divine Intervention", summary: "Solicitud de ayuda divina excepcional." },
    ],
  },
  {
    id: "druid",
    name: "Druid",
    source: "SRD 5.1",
    description:
      "Lanzador natural preparado con formas salvajes y magia de Sabiduría.",
    hitDie: 8,
    primaryAbilities: ["WIS"],
    savingThrows: ["INT", "WIS"],
    armorTraining: ["Light Armor", "Medium Armor", "Shields"],
    weaponTraining: [
      "Clubs",
      "Daggers",
      "Darts",
      "Javelins",
      "Maces",
      "Quarterstaffs",
      "Scimitars",
      "Sickles",
      "Slings",
      "Spears",
    ],
    toolTraining: ["Herbalism Kit"],
    skillChoices: [
      "Arcana",
      "Animal Handling",
      "Insight",
      "Medicine",
      "Nature",
      "Perception",
      "Religion",
      "Survival",
    ],
    skillChoiceCount: 2,
    spellcastingType: "FULL_PREPARED",
    spellcastingAbility: "WIS",
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Spellcasting", summary: "Lanzamiento de conjuros preparado basado en Sabiduría." },
      { level: 1, name: "Druidic", summary: "Lenguaje secreto druídico." },
      { level: 2, name: "Wild Shape", summary: "Transformación en bestias." },
      { level: 2, name: "Druid Circle", summary: "Elección de círculo druídico." },
      { level: 18, name: "Timeless Body", summary: "Envejecimiento ralentizado." },
      { level: 18, name: "Beast Spells", summary: "Lanzamiento de conjuros en forma salvaje." },
    ],
  },
  {
    id: "fighter",
    name: "Fighter",
    source: "SRD 5.1",
    description:
      "Combatiente marcial flexible con muchas mejoras y ataques adicionales.",
    hitDie: 10,
    primaryAbilities: ["STR", "DEX"],
    savingThrows: ["STR", "CON"],
    armorTraining: ["All Armor", "Shields"],
    weaponTraining: ["Simple Weapons", "Martial Weapons"],
    toolTraining: [],
    skillChoices: [
      "Acrobatics",
      "Animal Handling",
      "Athletics",
      "History",
      "Insight",
      "Intimidation",
      "Perception",
      "Survival",
    ],
    skillChoiceCount: 2,
    spellcastingType: "NONE",
    spellcastingAbility: null,
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Fighting Style", summary: "Especialización marcial." },
      { level: 1, name: "Second Wind", summary: "Recuperación personal breve." },
      { level: 2, name: "Action Surge", summary: "Acción adicional ocasional." },
      { level: 3, name: "Martial Archetype", summary: "Elección de arquetipo marcial." },
      { level: 5, name: "Extra Attack", summary: "Ataque adicional al atacar." },
      { level: 9, name: "Indomitable", summary: "Reintento de salvación fallida." },
    ],
  },
  {
    id: "monk",
    name: "Monk",
    source: "SRD 5.1",
    description:
      "Artista marcial ágil que usa Ki, movilidad y ataques sin armas.",
    hitDie: 8,
    primaryAbilities: ["DEX", "WIS"],
    savingThrows: ["STR", "DEX"],
    armorTraining: [],
    weaponTraining: ["Simple Weapons", "Shortswords"],
    toolTraining: ["One artisan tool or musical instrument"],
    skillChoices: [
      "Acrobatics",
      "Athletics",
      "History",
      "Insight",
      "Religion",
      "Stealth",
    ],
    skillChoiceCount: 2,
    spellcastingType: "NONE",
    spellcastingAbility: null,
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Unarmored Defense", summary: "Defensa sin armadura usando Sabiduría." },
      { level: 1, name: "Martial Arts", summary: "Combate sin armas y armas monásticas." },
      { level: 2, name: "Ki", summary: "Recurso para técnicas especiales." },
      { level: 2, name: "Unarmored Movement", summary: "Aumento de movilidad sin armadura." },
      { level: 3, name: "Monastic Tradition", summary: "Elección de tradición monástica." },
      { level: 5, name: "Extra Attack", summary: "Ataque adicional." },
      { level: 5, name: "Stunning Strike", summary: "Golpe que puede aturdir." },
    ],
  },
  {
    id: "paladin",
    name: "Paladin",
    source: "SRD 5.1",
    description:
      "Guerrero sagrado con juramento, auras, curación y magia parcial.",
    hitDie: 10,
    primaryAbilities: ["STR", "CHA"],
    savingThrows: ["WIS", "CHA"],
    armorTraining: ["All Armor", "Shields"],
    weaponTraining: ["Simple Weapons", "Martial Weapons"],
    toolTraining: [],
    skillChoices: [
      "Athletics",
      "Insight",
      "Intimidation",
      "Medicine",
      "Persuasion",
      "Religion",
    ],
    skillChoiceCount: 2,
    spellcastingType: "HALF_PREPARED_ROUNDED_DOWN",
    spellcastingAbility: "CHA",
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Divine Sense", summary: "Percepción de presencias sobrenaturales." },
      { level: 1, name: "Lay on Hands", summary: "Reserva de curación por toque." },
      { level: 2, name: "Fighting Style", summary: "Especialización marcial." },
      { level: 2, name: "Spellcasting", summary: "Lanzamiento de conjuros basado en Carisma." },
      { level: 2, name: "Divine Smite", summary: "Uso de magia para potenciar golpes." },
      { level: 3, name: "Sacred Oath", summary: "Elección de juramento sagrado." },
      { level: 5, name: "Extra Attack", summary: "Ataque adicional." },
      { level: 6, name: "Aura of Protection", summary: "Aura defensiva para salvaciones." },
    ],
  },
  {
    id: "ranger",
    name: "Ranger",
    source: "SRD 5.1",
    description:
      "Explorador marcial con magia parcial, rastreo y combate especializado.",
    hitDie: 10,
    primaryAbilities: ["DEX", "WIS"],
    savingThrows: ["STR", "DEX"],
    armorTraining: ["Light Armor", "Medium Armor", "Shields"],
    weaponTraining: ["Simple Weapons", "Martial Weapons"],
    toolTraining: [],
    skillChoices: [
      "Animal Handling",
      "Athletics",
      "Insight",
      "Investigation",
      "Nature",
      "Perception",
      "Stealth",
      "Survival",
    ],
    skillChoiceCount: 3,
    spellcastingType: "HALF_KNOWN_ROUNDED_DOWN",
    spellcastingAbility: "WIS",
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Favored Enemy", summary: "Especialización contra ciertos enemigos." },
      { level: 1, name: "Natural Explorer", summary: "Especialización en exploración." },
      { level: 2, name: "Fighting Style", summary: "Especialización marcial." },
      { level: 2, name: "Spellcasting", summary: "Lanzamiento de conjuros basado en Sabiduría." },
      { level: 3, name: "Ranger Archetype", summary: "Elección de arquetipo de explorador." },
      { level: 5, name: "Extra Attack", summary: "Ataque adicional." },
    ],
  },
  {
    id: "rogue",
    name: "Rogue",
    source: "SRD 5.1",
    description:
      "Especialista ágil con sigilo, habilidades, ataques precisos y evasión.",
    hitDie: 8,
    primaryAbilities: ["DEX"],
    savingThrows: ["DEX", "INT"],
    armorTraining: ["Light Armor"],
    weaponTraining: [
      "Simple Weapons",
      "Hand Crossbows",
      "Longswords",
      "Rapiers",
      "Shortswords",
    ],
    toolTraining: ["Thieves' Tools"],
    skillChoices: [
      "Acrobatics",
      "Athletics",
      "Deception",
      "Insight",
      "Intimidation",
      "Investigation",
      "Perception",
      "Performance",
      "Persuasion",
      "Sleight of Hand",
      "Stealth",
    ],
    skillChoiceCount: 4,
    spellcastingType: "NONE",
    spellcastingAbility: null,
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Expertise", summary: "Mejora competencias elegidas." },
      { level: 1, name: "Sneak Attack", summary: "Daño adicional en ataques precisos." },
      { level: 1, name: "Thieves' Cant", summary: "Jerga secreta criminal." },
      { level: 2, name: "Cunning Action", summary: "Acciones ágiles como acción adicional." },
      { level: 3, name: "Roguish Archetype", summary: "Elección de arquetipo de pícaro." },
      { level: 5, name: "Uncanny Dodge", summary: "Reduce daño recibido de un ataque." },
      { level: 7, name: "Evasion", summary: "Mejora contra efectos de área." },
    ],
  },
  {
    id: "sorcerer",
    name: "Sorcerer",
    source: "SRD 5.1",
    description:
      "Lanzador espontáneo basado en Carisma con origen mágico y metamagia.",
    hitDie: 6,
    primaryAbilities: ["CHA"],
    savingThrows: ["CON", "CHA"],
    armorTraining: [],
    weaponTraining: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    toolTraining: [],
    skillChoices: [
      "Arcana",
      "Deception",
      "Insight",
      "Intimidation",
      "Persuasion",
      "Religion",
    ],
    skillChoiceCount: 2,
    spellcastingType: "FULL_KNOWN",
    spellcastingAbility: "CHA",
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Spellcasting", summary: "Lanzamiento de conjuros basado en Carisma." },
      { level: 1, name: "Sorcerous Origin", summary: "Elección de origen mágico." },
      { level: 2, name: "Font of Magic", summary: "Recurso mágico flexible." },
      { level: 3, name: "Metamagic", summary: "Modifica la forma de lanzar conjuros." },
      { level: 20, name: "Sorcerous Restoration", summary: "Recuperación de recurso mágico." },
    ],
  },
  {
    id: "warlock",
    name: "Warlock",
    source: "SRD 5.1",
    description:
      "Lanzador pactado basado en Carisma, invocaciones y magia de pacto.",
    hitDie: 8,
    primaryAbilities: ["CHA"],
    savingThrows: ["WIS", "CHA"],
    armorTraining: ["Light Armor"],
    weaponTraining: ["Simple Weapons"],
    toolTraining: [],
    skillChoices: [
      "Arcana",
      "Deception",
      "History",
      "Intimidation",
      "Investigation",
      "Nature",
      "Religion",
    ],
    skillChoiceCount: 2,
    spellcastingType: "PACT_MAGIC",
    spellcastingAbility: "CHA",
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Otherworldly Patron", summary: "Elección de patrón sobrenatural." },
      { level: 1, name: "Pact Magic", summary: "Magia pactada con recuperación rápida." },
      { level: 2, name: "Eldritch Invocations", summary: "Opciones mágicas permanentes." },
      { level: 3, name: "Pact Boon", summary: "Beneficio especial del pacto." },
      { level: 11, name: "Mystic Arcanum", summary: "Acceso a magia superior limitada." },
      { level: 20, name: "Eldritch Master", summary: "Recuperación final de magia pactada." },
    ],
  },
  {
    id: "wizard",
    name: "Wizard",
    source: "SRD 5.1",
    description:
      "Lanzador académico basado en Inteligencia, libro de conjuros y escuelas.",
    hitDie: 6,
    primaryAbilities: ["INT"],
    savingThrows: ["INT", "WIS"],
    armorTraining: [],
    weaponTraining: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    toolTraining: [],
    skillChoices: [
      "Arcana",
      "History",
      "Insight",
      "Investigation",
      "Medicine",
      "Religion",
    ],
    skillChoiceCount: 2,
    spellcastingType: "FULL_PREPARED_SPELLBOOK",
    spellcastingAbility: "INT",
    isOfficial: true,
    isSrd: true,
    features: [
      { level: 1, name: "Spellcasting", summary: "Lanzamiento de conjuros basado en Inteligencia y libro de conjuros." },
      { level: 1, name: "Arcane Recovery", summary: "Recuperación parcial de espacios de conjuro." },
      { level: 2, name: "Arcane Tradition", summary: "Elección de tradición arcana." },
      { level: 18, name: "Spell Mastery", summary: "Dominio de conjuros de bajo nivel." },
      { level: 20, name: "Signature Spell", summary: "Conjuros característicos de uso mejorado." },
    ],
  },
];

async function main() {
  for (const classPreset of classPresets) {
    const { features, ...classData } = classPreset;

    await prisma.classPreset.upsert({
      where: {
        id: classPreset.id,
      },
      update: classData,
      create: classData,
    });

    await prisma.classFeaturePreset.deleteMany({
      where: {
        classPresetId: classPreset.id,
      },
    });

    for (const feature of features) {
      await prisma.classFeaturePreset.create({
        data: {
          classPresetId: classPreset.id,
          level: feature.level,
          name: feature.name,
          summary: feature.summary,
        },
      });
    }
  }

  console.log(`Seed completo: ${classPresets.length} clases cargadas.`);
}

main()
  .catch((error) => {
    console.error("Error cargando presets de clases:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });